name: <%= name.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`).slice(1) %>
version: 0.0.1
summary: Your ReactNative Ubuntu Application
description: This is a description of <%= name %>
confinement: devmode
apps:
  <%= name %>:
    command: bin/<%= name %> --local=./share/js/index.js --plugins-path=./plugins

parts:
  nodejs:
    plugin: nodejs

  react-native-app:
    plugin: copy
    source: ..
    files:
      bin/<%= name %>: bin/<%= name %>
      bin/ubuntu-server.js: bin/ubuntu-server.js
      share: share
      plugins: plugins

